#LIBERIES

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import silhouette_score
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

#UPLOADED DATASETS

In [ ]:
df = pd.read_csv("/content/sample_data/Shopping_table_customer_segmentation1.csv")
df1 = pd.read_csv("/content/sample_data/std_customer_segmentation1.csv")
df.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount_USD,Location,Size,Color,Season,Review_Rating,Subscription_Status,Payment_Method,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Preferred_Payment_Method,Frequency_of_Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df1.head()

,CustomerID,Age,Gender,ItemPurchased,Category,PurchaseAmountUSD,Location,Size,Color,Season,ReviewRating,SubscriptionStatus,ShippingType,DiscountApplied,PromoCodeUsed,PreviousPurchases,PaymentMethod,FrequencyOfPurchases,Age_Group
0,1,56,Male,Bag,Accessories,374.86,New York,L,Red,Fall,3,No,Standard,Yes,No,7,PayPal,Fortnightly,50s
1,2,46,Male,Shoes,Home Decor,33.28,Los Angeles,S,Black,Spring,2,No,Express,Yes,No,3,UPI,Weekly,40s
2,3,32,Female,Laptop,Home Decor,117.45,Houston,S,Black,Fall,4,No,Standard,Yes,Yes,13,UPI,Monthly,30s
3,4,60,Male,Bag,Home Decor,356.05,Chicago,M,Green,Summer,2,Yes,Express,No,No,14,PayPal,Weekly,60+
4,5,25,Female,Laptop,Accessories,393.50,Houston,M,Black,Winter,2,Yes,Express,No,No,5,Cash,Fortnightly,20s

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               1000 non-null   int64
 1   Age                       1000 non-null   int64
 2   Gender                    1000 non-null   object
 3   Item_Purchased            1000 non-null   object
 4   Category                  1000 non-null   object
 5   Purchase_Amount_USD       1000 non-null   int64
 6   Location                  1000 non-null   object
 7   Size                      1000 non-null   object
 8   Color                     1000 non-null   object
 9   Season                    1000 non-null   object
 10  Review_Rating             1000 non-null   float64
 11  Subscription_Status       1000 non-null   object
 12  Payment_Method            1000 non-null   object
 13  Shipping_Type             1000 non-null   object
 14  Discount_Applied          1000 non-null   object
 15  Promo_Code_Used           1000 non-null   object
 16  Previous_Purchases        1000 non-null   int64
 17  Preferred_Payment_Method  1000 non-null   object
 18  Frequency_of_Purchases    1000 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 148.6+ KB

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            1000 non-null   int64
 1   Age                   1000 non-null   int64
 2   Gender                1000 non-null   object
 3   ItemPurchased         1000 non-null   object
 4   Category              1000 non-null   object
 5   PurchaseAmountUSD     1000 non-null   float64
 6   Location              1000 non-null   object
 7   Size                  1000 non-null   object
 8   Color                 1000 non-null   object
 9   Season                1000 non-null   object
 10  ReviewRating          1000 non-null   int64
 11  SubscriptionStatus    1000 non-null   object
 12  ShippingType          1000 non-null   object
 13  DiscountApplied       1000 non-null   object
 14  PromoCodeUsed         1000 non-null   object
 15  PreviousPurchases     1000 non-null   int64
 16  PaymentMethod         1000 non-null   object
 17  FrequencyOfPurchases  1000 non-null   object
 18  Age_Group             1000 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 148.6+ KB

In [ ]:
df.describe()

,Customer_ID,Age,Purchase_Amount_USD,Review_Rating,Previous_Purchases
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,44.225000,59.653000,3.741400,26.199000
std,288.819436,15.068491,23.415313,0.716952,14.071084
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,250.750000,31.000000,39.000000,3.100000,14.000000
50%,500.500000,45.000000,60.000000,3.700000,26.000000
75%,750.250000,57.000000,80.000000,4.400000,38.000000
max,1000.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
df1.describe()

,CustomerID,Age,PurchaseAmountUSD,ReviewRating,PreviousPurchases
count,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,500.500000,40.986000,259.394050,2.98400,6.922000
std,288.819436,13.497852,140.865429,1.38335,4.282786
min,1.000000,18.000000,10.120000,1.00000,0.000000
25%,250.750000,29.000000,136.657500,2.00000,3.000000
50%,500.500000,42.000000,260.565000,3.00000,7.000000
75%,750.250000,52.000000,382.352500,4.00000,11.000000
max,1000.000000,64.000000,499.760000,5.00000,14.000000

# Categorical

In [ ]:
df.fillna(df.mean(numeric_only=True),inplace=True)
df.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount_USD,Location,Size,Color,Season,Review_Rating,Subscription_Status,Payment_Method,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Preferred_Payment_Method,Frequency_of_Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
for col in df1.select_dtypes(include='object'):
  df1[col]=df1[col].fillna(df1[col].mode()[0])
df1.head()

,CustomerID,Age,Gender,ItemPurchased,Category,PurchaseAmountUSD,Location,Size,Color,Season,ReviewRating,SubscriptionStatus,ShippingType,DiscountApplied,PromoCodeUsed,PreviousPurchases,PaymentMethod,FrequencyOfPurchases,Age_Group
0,1,56,Male,Bag,Accessories,374.86,New York,L,Red,Fall,3,No,Standard,Yes,No,7,PayPal,Fortnightly,50s
1,2,46,Male,Shoes,Home Decor,33.28,Los Angeles,S,Black,Spring,2,No,Express,Yes,No,3,UPI,Weekly,40s
2,3,32,Female,Laptop,Home Decor,117.45,Houston,S,Black,Fall,4,No,Standard,Yes,Yes,13,UPI,Monthly,30s
3,4,60,Male,Bag,Home Decor,356.05,Chicago,M,Green,Summer,2,Yes,Express,No,No,14,PayPal,Weekly,60+
4,5,25,Female,Laptop,Accessories,393.50,Houston,M,Black,Winter,2,Yes,Express,No,No,5,Cash,Fortnightly,20s

#MERGE_DATASETS

In [ ]:
Customer = pd.merge(df,df1,
                    left_on='Customer_ID',right_on='CustomerID',how="left")
Customer.head()

,Customer_ID,Age_x,Gender_x,Item_Purchased,Category_x,Purchase_Amount_USD,Location_x,Size_x,Color_x,Season_x,...,Season_y,ReviewRating,SubscriptionStatus,ShippingType,DiscountApplied,PromoCodeUsed,PreviousPurchases,PaymentMethod,FrequencyOfPurchases,Age_Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Fall,3,No,Standard,Yes,No,7,PayPal,Fortnightly,50s
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Spring,2,No,Express,Yes,No,3,UPI,Weekly,40s
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Fall,4,No,Standard,Yes,Yes,13,UPI,Monthly,30s
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Summer,2,Yes,Express,No,No,14,PayPal,Weekly,60+
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Winter,2,Yes,Express,No,No,5,Cash,Fortnightly,20s

#AGE_GROUP

In [ ]:
Customer['Age_Group']=pd.cut(Customer['Age_x'],
          bins=[0,30,45,60,75],
          labels=["Younger","ADULTS","MID-ADULT","SENIOR"])
Customer.head()

,Customer_ID,Age_x,Gender_x,Item_Purchased,Category_x,Purchase_Amount_USD,Location_x,Size_x,Color_x,Season_x,...,Season_y,ReviewRating,SubscriptionStatus,ShippingType,DiscountApplied,PromoCodeUsed,PreviousPurchases,PaymentMethod,FrequencyOfPurchases,Age_Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Fall,3,No,Standard,Yes,No,7,PayPal,Fortnightly,MID-ADULT
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Spring,2,No,Express,Yes,No,3,UPI,Weekly,Younger
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Fall,4,No,Standard,Yes,Yes,13,UPI,Monthly,MID-ADULT
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Summer,2,Yes,Express,No,No,14,PayPal,Weekly,Younger
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Winter,2,Yes,Express,No,No,5,Cash,Fortnightly,ADULTS

#FREQUENCY_VISTORS_MAPPING

In [ ]:
Feq_map ={
    "Weekly":4,"Bi-Weekly":4,
    "Monthly":12,"Quarterly":48,
    "Yearly":5216,"Annually": 2,
    "Fortnightly":3,"Every 3 Months":3

}
Customer['FrequencyOfPurchases']=Customer['FrequencyOfPurchases'].map(Feq_map)
Customer.head()

,Customer_ID,Age_x,Gender_x,Item_Purchased,Category_x,Purchase_Amount_USD,Location_x,Size_x,Color_x,Season_x,...,Season_y,ReviewRating,SubscriptionStatus,ShippingType,DiscountApplied,PromoCodeUsed,PreviousPurchases,PaymentMethod,FrequencyOfPurchases,Age_Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Fall,3,No,Standard,Yes,No,7,PayPal,3,MID-ADULT
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Spring,2,No,Express,Yes,No,3,UPI,4,Younger
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Fall,4,No,Standard,Yes,Yes,13,UPI,12,MID-ADULT
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Summer,2,Yes,Express,No,No,14,PayPal,4,Younger
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Winter,2,Yes,Express,No,No,5,Cash,3,ADULTS

#TOTAL_SPENDING

In [ ]:
Customer['Purchase_Amount_USD']=Customer.groupby("Customer_ID")["Purchase_Amount_USD"].transform(lambda x:x.sum())
Customer.head()

,Customer_ID,Age_x,Gender_x,Item_Purchased,Category_x,Purchase_Amount_USD,Location_x,Size_x,Color_x,Season_x,...,Season_y,ReviewRating,SubscriptionStatus,ShippingType,DiscountApplied,PromoCodeUsed,PreviousPurchases,PaymentMethod,FrequencyOfPurchases,Age_Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Fall,3,No,Standard,Yes,No,7,PayPal,3,MID-ADULT
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Spring,2,No,Express,Yes,No,3,UPI,4,Younger
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Fall,4,No,Standard,Yes,Yes,13,UPI,12,MID-ADULT
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Summer,2,Yes,Express,No,No,14,PayPal,4,Younger
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Winter,2,Yes,Express,No,No,5,Cash,3,ADULTS

#EXPLORATORY DATA ANALYSIS (EDA)_CUSTOMER_SEGMENTATION

In [ ]:
fig = px.histogram(Customer, x="Age_Group", title="AGE_GROUP_CUSTOMERS",
                   hover_data=["Season_x"],text_auto=True,
                   color_discrete_sequence=["Green"],
                   category_orders={"Age_Group": ["Younger", "ADULTS", "MID-ADULT", "SENIOR"]},
                   width=800, height=500,
                   template="plotly_dark",
                   labels={"Age_Group": "Age Group"},
                   color_discrete_map={"Younger": "Green", "ADULTS": "Blue", "MID-ADULT": "GREY", "SENIOR": "Black"}
                   )

fig.update_xaxes(categoryorder="array", categoryarray=Customer["Age_Group"].value_counts().index)
fig.update_traces(marker_color='Green', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5)
fig.update_layout(bargap=0.1, showlegend=False)
fig.show()

#ITEM ON SEASON FREQUENTLY PURCHASED

In [ ]:
fig = px.histogram(Customer, x="Item_Purchased", title="ITEM_ON_SEASON_FREQUENTLY_PURCHASED", text_auto=True)
fig.update_xaxes(categoryorder="array", categoryarray=Customer["Item_Purchased"].value_counts().index)
fig.update_traces(marker_color='Green', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5)
fig.update_layout(bargap=0.1, showlegend=False)
fig.show()

#SEASONWISEPURCHSED

In [ ]:
#3D
fig = px.scatter_3d(Customer, x="Season_x", y="Item_Purchased", z="Purchase_Amount_USD",
                    color="Season_x")
fig.show()

#REVIEWRATING__SUBSCRTION_STATUS

In [ ]:
fig = px.pie(
    Customer,
    values='ReviewRating',
    names='SubscriptionStatus',
    title='Review Rating by Subscription Status',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    hole=0.3,
    labels={'ReviewRating': 'Review Rating', 'SubscriptionStatus': 'Subscription Status'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Season_x'],
    category_orders={'SubscriptionStatus': ['Yes', 'No']}
)
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(legend_title_text='Subscription Status')
fig.show()

#AGE_GROUP_SEASON_SHIPPING

In [ ]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

Customer_Polar = Customer.groupby(['Age_Group', 'Season_x'])['ShippingType'].value_counts(normalize=True).unstack().reset_index()
Customer_Polar.head()

/tmp/ipykernel_1365/1862202037.py:4: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

ShippingType Age_Group Season_x   Express  Standard
0              Younger     Fall  0.480000  0.520000
1              Younger   Spring  0.508475  0.491525
2              Younger   Summer  0.544118  0.455882
3              Younger   Winter  0.491525  0.508475
4               ADULTS     Fall  0.493151  0.506849

In [ ]:
Customer_Polar_melted = Customer_Polar.melt(
    id_vars=['Age_Group', 'Season_x'],
    value_vars=['Express', 'Standard'],
    var_name='Shipping_Type',
    value_name='Proportion'
)

fig = px.bar_polar(
    Customer_Polar_melted,
    r="Proportion",
    theta="Season_x",
    color="Shipping_Type",
    animation_frame="Age_Group",
    title="CUSTOMER_AGE_GROUP_SEASON_SHIPPING",
    template="plotly_dark",
    color_discrete_sequence=px.colors.qualitative.Pastel,
    category_orders={"Age_Group": ["Younger", "ADULTS", "MID-ADULT", "SENIOR"]}
)
fig.update_traces(marker_line_width=2, opacity=0.6)
fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)
fig.show()

#LOCATION_HIGHEST_ITEM_SOLIDOUT

In [ ]:
fig = px.bar(
    Customer,
    x='Location_x',
    y='Item_Purchased',
    color='Item_Purchased',
    barmode='group',
    text_auto='.2s',
    hover_data=['Season_x'],
    title='LOCATION_HIGHEST_ITEM_SOLIDOUT',
    template='plotly_dark', # Corrected template name
    color_discrete_sequence=px.colors.qualitative.Pastel,
    category_orders={'Location': Customer['Location_x'].value_counts().index}
)
fig.update_layout(bargap=0.7, xaxis_tickangle=-45)
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5)
fig.show()

In [ ]:
fig = px.bar(
    Customer,
    x='Location_y',
    y='Item_Purchased',
    color='Item_Purchased',
    barmode='group',
    text_auto='.2s',
    hover_data=['Season_y'],
    title='LOCATION_HIGHEST_ITEM_SOLIDOUT',
    template='plotly_dark', # Corrected template name
    color_discrete_sequence=px.colors.qualitative.Pastel,
    category_orders={'Location': Customer['Location_y'].value_counts().index}
)
fig.update_layout(bargap=0.7, xaxis_tickangle=-45)
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5)
fig.show()

#DISCOUNT_APPLIED_ITEM_PURCHASED_CATEGORYWISE

In [ ]:
fig = px.bar(
    Customer,
    x='Category_x',
    color='DiscountApplied',
    animation_frame="Age_Group",
    title='DISCOUNT_APPLIED_ITEM_PURCHASED_CATEGORYWISE',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels={'DiscountApplied': 'Discount Applied', 'Category_x': 'Category'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Season_x'],
    category_orders={'Category_x': Customer['Category_x'].value_counts().index.tolist()},
    text_auto=True
)
fig.update_layout(legend_title_text='Discount Applied Status')
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5)
fig.show()

#PROMOCODE_ITEM_PREVISOULY_PURCHASED

In [ ]:
fig = px.bar(
    Customer,
    x='Item_Purchased',
    color='PromoCodeUsed',
    animation_frame="Category_y",
    title='PROMOCODE_ITEM_PREVISOULY_PURCHASED',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels={'PromoCodeUsed': 'Promo Code Used', 'Item_Purchased': 'Item Purchased'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Category_x'],
    category_orders={'Item_Purchased': Customer['Item_Purchased'].value_counts().index.tolist()},
    text_auto=True,
    barmode='group'
)
fig.update_layout(legend_title_text='Promo Code Used Status')
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5)
fig.show()

#PAYMNET_METHOD_AGE_GROUP_CATEGORY

In [ ]:
fig=px.density_heatmap(
    Customer,
    x='Age_Group',
    y='Payment_Method',
    animation_frame='Category_x',
    title='PAYMNET_METHOD_AGE_GROUP_CATEGORY',
    labels={'Payment_Method': 'Payment Method', 'Age_Group': 'Age Group'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Season_x'],
    category_orders={'Age_Group': ['Younger', 'ADULTS', 'MID-ADULT', 'SENIOR']}
)
fig.update_layout(legend_title_text='Age Group')
fig.show()

In [ ]:
fig=px.density_heatmap(
    Customer,
    x='Age_Group',
    y='Payment_Method',
    animation_frame='Location_x',
    title='PAYMNET_METHOD_AGE_GROUP_CATEGORY',
    labels={'Payment_Method': 'Payment Method', 'Age_Group': 'Age Group'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Season_x'],
    category_orders={'Age_Group': ['Younger', 'ADULTS', 'MID-ADULT', 'SENIOR']}
)
fig.update_layout(legend_title_text='Age Group')
fig.show()

In [ ]:
fig=px.density_heatmap(
    Customer,
    x='Age_Group',
    y='Payment_Method',
    animation_frame='Location_y',
    title='PAYMNET_METHOD_AGE_GROUP_CATEGORY',
    labels={'Payment_Method': 'Payment Method', 'Age_Group': 'Age Group'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Season_x'],
    category_orders={'Age_Group': ['Younger', 'ADULTS', 'MID-ADULT', 'SENIOR']}
)
fig.update_layout(legend_title_text='Age Group')
fig.show()

#SHIPING TYPE_ITEM_CATEGORY_PAYMENT_PURCHASED

In [ ]:
fig = px.bar(
    Customer,
    x='Category_x',
    color='ShippingType',
    animation_frame="Payment_Method",
    title='SHIPING TYPE_ITEM_CATEGORY_PAYMENT_PURCHASED',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels={'ShippingType': 'Shipping Type', 'Category_x': 'Category'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Item_Purchased'],
    category_orders={'Category_x': Customer['Category_x'].value_counts().index.tolist()},
    text_auto=True
    )
fig.update_layout(legend_title_text='Shipping Type')
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5)
fig.show()

#LOCATION_CATEGORY_SALES

In [ ]:
fig = px.area(
    Customer,
    x='Location_x',
    y='Purchase_Amount_USD',
    color='Category_x',
    animation_frame="Age_Group",
    hover_data=['Season_x'],
    title='LOCATION_CATEGORY_SALES',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels={'Purchase_Amount_USD': 'Purchase Amount', 'Category_x': 'Category'},
    template='plotly_dark',
    width=800,
    height=500,
    category_orders={'Category_x': Customer['Category_x'].value_counts().index.tolist()}
    )
fig.update_layout(legend_title_text='Category')
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5,
                  )
fig.update_traces(
    texttemplate='%{y}'
)
fig.update_traces(fill='toself')
fig.show()

In [ ]:
fig = px.area(
    Customer,
    x='Location_y',
    y='Purchase_Amount_USD',
    color='Category_x',
    animation_frame="Age_Group",
    hover_data=['Season_y'],
    title='LOCATION_CATEGORY_SALES',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels={'Purchase_Amount_USD': 'Purchase Amount', 'Category_y': 'Category'},
    template='plotly_dark',
    width=800,
    height=500,
    category_orders={'Category_y': Customer['Category_y'].value_counts().index.tolist()}
    )
fig.update_layout(legend_title_text='Category')
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5,
                  )
fig.update_traces(
    texttemplate='%{y}'
)
fig.update_traces(fill='toself')
fig.show()

In [ ]:
# geolocator = Nominatim(user_agent="geo_app")
# geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
# Customer['Location'] = Customer['Location_x'].apply(geocode)
# Customer['Location'] = Customer['Location_y'].apply(geocode)
# Customer['Location'] = Customer['Location_x'].apply(lambda loc: tuple(loc.point) if loc else None)
# Customer['Location'] = Customer['Location_y'].apply(lambda loc: tuple(loc.point) if loc else None)
# Customer[['Latitude', 'Longitude', 'Altitude']] = pd.DataFrame(Customer['Location'].tolist(), index=Customer.index)
# Customer.head()

#SIZE_ITEM_PURCHASED_CUSTOMER

In [ ]:
fig = px.bar(
    Customer,
    x='Item_Purchased',
    color='Size_x',
    animation_frame="Age_Group",
    title='SIZE_ITEM_PURCHASED_CUSTOMER',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels={'Size_x': 'Size', 'Item_Purchased': 'Item Purchased'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Season_x'],
    category_orders={'Item_Purchased': Customer['Item_Purchased'].value_counts().index.tolist()},
    text_auto=True
)
fig.update_layout(legend_title_text='Size')
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5)
fig.show()

In [ ]:
fig = px.bar(
    Customer,
    x='Item_Purchased',
    color='Size_y',
    animation_frame="Age_Group",
    title='SIZE_ITEM_PURCHASED_CUSTOMER',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels={'Size_y': 'Size', 'Item_Purchased': 'Item Purchased'},
    template='plotly_dark',
    width=800,
    height=500,
    hover_data=['Season_y'],
    category_orders={'Item_Purchased': Customer['Item_Purchased'].value_counts().index.tolist()},
    text_auto=True
)
fig.update_layout(legend_title_text='Size')
fig.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5)
fig.update_traces(
    texttemplate='%{y}'
)
fig.show()

#CUSTOMER SEGMENTATION(K_MEANS)

In [ ]:
# Select the features for clustering
features_Customer = Customer[["Age_Group", "FrequencyOfPurchases", "Purchase_Amount_USD"]]

# One-hot encode the 'Age_Group' categorical column
features_Customer = pd.get_dummies(features_Customer, columns=['Age_Group'], drop_first=True)

# Scale the numerical features
scaler = StandardScaler()
Features_scaled = scaler.fit_transform(features_Customer)

# Initialize and fit the KMeans model
KMEANS = KMeans(n_clusters=4, random_state=42, n_init=10) # Added n_init to suppress warning
KMEANS.fit(Features_scaled)

KMeans(n_clusters=4, n_init=10, random_state=42)

In [ ]:
Customer['Cluster'] = KMEANS.labels_

fig = px.scatter_3d(Customer, x='FrequencyOfPurchases', y='Purchase_Amount_USD', z='Age_Group',
                    color='Cluster', title='Customer Segments by Purchase Behavior and Age Group')
fig.show()

#SEGMENT EVALUATION_Frequency_Purchase

In [ ]:
# Calculate silhouette score
silhouette_AVG = silhouette_score(Features_scaled, KMEANS.labels_)
print("Silhouette Score:", silhouette_AVG)

Silhouette Score: 0.40628528552009197

In [ ]:
x=features_Customer
y=Customer["FrequencyOfPurchases"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       1.00      1.00      1.00        65
           4       1.00      1.00      1.00        67
          12       1.00      1.00      1.00        68

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200